---
driver:
  name: vagrant
  network:
  - ["forwarded_port", {guest: 5601, host: 5601, auto_correct: true}]
  - ["forwarded_port", {guest: 443, host: 8443, auto_correct: true}]
  - ["forwarded_port", {guest: 80, host: 880, auto_correct: true}]

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[non-prod-elk-stack::default]
    attributes:
